# Generated by Django 5.1.1 on 2024-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=100),
        ),
    ]
