# Generated by Django 5.1.1 on 2024-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_city_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
    ]
